name: Warstwa Frontend aplikacji internetowej
on: 
  push:
    branches:
      - main
      - frontend
  pull_request:
    branches:
      - main
      - frontend
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["16","18"]
    steps:
      - name: Pobranie kodu z repozytorium
        uses: actions/checkout@v3
      - name: Dołącznie Node.js
        uses: actions/setup-node@v2
        with:
          node_version: "16.18.0"

      - name: Instalacja dependencji
        run: npm install
      - name: Kompilacja aplikacji
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Pobranie kodu z repozytorium
        uses: actions/checkout@v3
      - name: Podłączenie usługi Azure App Services
        uses: azure/appservice-build@v3
        with:
          platform: nodejs
          platform-version: 16.18.0
      - name: Wdrażanie aplikacji na Azure App Services
        uses: azure/webapps-deploy@v1
        with:
          app-name: frontend-app-tn
          publish-profile: ${{secrets.AZURE_WEB_APP_PUBLISH_PROFILE}}


